version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "stachu540"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "stachu540"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "stachu540"
