name-template: 'v$RESOLVED_VERSION'
tag-template: $RESOLVED_VERSION
categories:
  - title: General Changes
    lables:
      - refactor
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: Documentation
    labels:
      - docs
      - documentation
  - title: Dependency Updates
    label:
      - dependencies
version-resolver:
  major:
    labels:
      - refactor
  minor:
    labels:
      - feature
      - enhancement
  patch:
    labels:
      - docs
      - documentation
      - dependencies
      - bug
prerelease: false
template: |
  ## What's new

  $CHANGES
exclude-labels:
  - skip-log
