site_name: Alice
repo_name: Alice
repo_url: https://github.com/stachu540/ALICE
site_description: "Multi-purpose bot environment"
site_author: Damian Staszewski
remote_branch: gh-pages
site_url: https://stachu540.github.io/ALICE

theme:
  feature:
    tabs: true
  name: 'material'
  favicon: false
  logo: false
  palette:
    primary: yellow
    accent: blue

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Overview': index.md
  - 'Getting Started': getting_started.md
  # - 'Works with ALICE': works_with_alice.md
  - 'Releases': https://github.com/stachu540/ALICE/releases
  # - 'Upgrading to OkHttp 4': upgrading_to_okhttp_4.md
  # - 'Contributing': contributing.md
  # - 'Code of Conduct': code_of_conduct.md