package io.alice.platform.plugin

import java.nio.file.Path
import java.time.Instant
import java.time.format.DateTimeFormatter
import java.util.*
import kotlin.io.path.outputStream

object Platform {
    val Version: String = "#{alice.platform.version}"
    val Group: String = "#{alice.platform.group}"
    val Name: String = "alice-api"
}

class ModuleGenerator {
    private val modules = mutableSetOf<ModuleSpec>()

    fun add(spec: ModuleSpec) {
        modules.add(spec)
    }

    fun processResources(resourcePath: Path) {
        for (module in modules) {
            module.createResource(resourcePath)
        }
    }
}

data class ModuleSpec(
    val id: String,
    val type: TypeSpec,
    val path: String
) {
    enum class TypeSpec {
        CLASSPATH, ALIAS
    }

    fun createResource(resourcePath: Path) {
        val props = generateProperties()
        val timestamp = DateTimeFormatter.ISO_INSTANT.format(Instant.now())
        resourcePath.resolve("META-INF/alice/modules/${id}.properties").outputStream().use {
            props.store(it, "Generated by Alice Platform Plugin [$timestamp]")
        }
    }

    fun generateProperties(): Properties {
        val properties = Properties()
        when (type) {
            TypeSpec.CLASSPATH -> {
                properties.setProperty("implementation-class", path)
            }

            TypeSpec.ALIAS -> {
                properties.setProperty("alias", path)
            }
        }

        return properties
    }
}