name: Github Pages

on:
  push:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        name: Checkout
      - uses: actions/setup-java@v2
        name: Setup JDK8
        with:
          java-version: 8
          distribution: zulu
      - name: Deploy KDoc
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: dokkaHtmlCollector
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/htmlCollector
          cname: api.aliceplatform.io
