name: Gradle Wrapper Update
on:
  schedule:
    - cron: 0 6 * * TUE # Check updates each Tuesday on 6AM UTC

jobs:
  gradle_update:
    name: Gradle Update Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - run: git branch deps/gradle-updates
      - name: Gradle Wrapper Check
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          reviewers: stachu540
          labels: dependencies
