name: Gradle Wrapper Validate
on:
  push:
    paths-ignore:
      - '**.md'
      - docs/**
      - .github/workflows/**
      - .gitignore
      - .editorconfig

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: gradle/wrapper-validation-action@v1.0.3
        name: Wrapper Validation
