name: Release
on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: Release Notes
        required: true

env:
  CI: true
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORSSH_USER: ${{ secrets.ORSSH_USER }}
  ORSSH_PASSPHRASE: ${{ secrets.ORSSH_PASSPHRASE }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_KEY: ${{ secrets.GPG_KEY }}

jobs:
  test:
    name: Release Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm: [ 8, 11, 15 ]
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: actions/cache@v2.1.4
        name: Cache JDK${{ matrix.jvm }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: JDK${{ matrix.jvm }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: JDK${{ matrix.jvm }}-gradle-
      - uses: actions/setup-java@v2
        name: Setup JDK${{ matrix.jvm }}
        with:
          java-version: ${{ matrix.jvm }}
          distribution: zulu
      - name: Final Test JDK${{ matrix.jvm }}
        uses: eskatos/gradle-command-action@v2.1.0
        with:
          arguments: check
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
        with:
          ref: main
      - uses: actions/cache@v2.1.4
        name: Cache JDK8
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: JDK8-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: JDK8-gradle-
      - uses: actions/setup-java@v2
        name: Setup JDK8
        with:
          java-version: 8
          distribution: zulu
      - name: Prepare Release
        uses: release-drafter/release-drafter@v5.15.0
        id: release
      - name: Release v${{ steps.release.outputs.tag_name }}
        uses: eskatos/gradle-command-action@v2.1.0
        with:
          arguments: publish -Pversion=${{ steps.release.outputs.tag_name }}
      - name: Publish Release Information to Discord Channel
        uses: sarisia/actions-status-discord@v1.8.5
        with:
          nodetail: true
          title: New version `${{ steps.release.outputs.tag_name }}` is ready!
          description: |
            \# [`v${{ steps.release.outputs.tag_name }}`](${{ steps.release.outputs.html_url }})
            ${{ steps.release.outputs.body }}
