name: Test
on:
  push:
    paths-ignore:
      - '**.md'
      - .github/workflows/**
      - docs/**
      - .gitignore
      - .editorconfig
      - mkdocs.yml
      - requirements.txt
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - docs/**
      - .github/workflows/**
      - .gitignore
      - .editorconfig
      - mkdocs.yml
      - requirements.txt

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  wrapper_validate:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: gradle/wrapper-validation-action@v1
        name: Validate Wrapper
  test:
    name: Test
    needs: [ wrapper_validate ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm: [ 8, 11, 15 ]
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: actions/cache@v2.1.4
        name: Cache JDK${{ matrix.jvm }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: JDK${{ matrix.jvm }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: JDK${{ matrix.jvm }}-gradle-
      - uses: actions/setup-java@v2
        name: Setup JDK${{ matrix.jvm }}
        with:
          java-version: ${{ matrix.jvm }}
          distribution: zulu
      - name: Test JDK${{ matrix.jvm }}
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: test
